name: ai_studio
description: Flutter Text, Voice, 3D Demo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.5.1
  flutter_cube: ^0.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/cube/cube.obj
