name: ai_studio
description: A new Flutter project.

# Yahan SDK ka constraint fix kiya gaya hai
environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  audioplayers: ^6.5.1
  flutter_cube: ^0.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/cube/cube.obj
    - assets/audio/test.mp3
